export const GET_QUIZ_LOADING = 'GET_QUIZ_LOADING';
export const GET_QUIZ_SUCCESS = 'GET_QUIZ_SUCCESS';
export const GET_QUIZ_ERROR = 'GET_QUIZ_ERROR';
export const CLEAR_QUIZ_STATE = 'CLEAR_QUIZ_STATE';

export const GET_PREVIOUS_SCORE_LOADING = 'GET_PREVIOUS_SCORE_LOADING';
export const GET_PREVIOUS_SCORE_SUCCESS = 'GET_PREVIOUS_SCORE_SUCCESS';
export const GET_PREVIOUS_SCORE_ERROR = 'GET_PREVIOUS_SCORE_ERROR';

export const SAVE_SCORE_ACTION_LOADING = 'SAVE_SCORE_ACTION_LOADING';
export const SAVE_SCORE_ACTION_SUCCESS = 'SAVE_SCORE_ACTION_SUCCESS';
export const SAVE_SCORE_ACTION_ERROR = 'SAVE_SCORE_ACTION_ERROR';

export const CREATE_USER_ACTION_LOADING = 'CREATE_USER_ACTION_LOADING';
export const CREATE_USER_ACTION_SUCCESS = 'CREATE_USER_ACTION_SUCCESS';
export const CREATE_USER_ACTION_ERROR = 'CREATE_USER_ACTION_ERROR';
export const CREATE_USER_CLEAR_STATE = 'CREATE_USER_CLEAR_STATE';

export const LOGIN_USER_ACTION_LOADING = 'LOGIN_USER_ACTION_LOADING';
export const LOGIN_USER_ACTION_SUCCESS = 'LOGIN_USER_ACTION_SUCCESS';
export const LOGIN_USER_ACTION_ERROR = 'LOGIN_USER_ACTION_ERROR';
export const LOGIN_USER_CLEAR_STATE = 'LOGIN_USER_CLEAR_STATE';

export const GET_USER_INFO_ACTION_LOADING = 'GET_USER_INFO_ACTION_LOADING';
export const GET_USER_INFO_ACTION_SUCCESS = 'GET_USER_INFO_ACTION_SUCCESS';
export const GET_USER_INFO_ACTION_ERROR = 'GET_USER_INFO_ACTION_ERROR';

export const UPDATE_USER_ACTION_LOADING = 'UPDATE_USER_ACTION_LOADING';
export const UPDATE_USER_ACTION_SUCCESS = 'UPDATE_USER_ACTION_SUCCESS';
export const UPDATE_USER_ACTION_ERROR = 'UPDATE_USER_ACTION_ERROR';

export const DELETE_USER_ACTION_LOADING = 'DELETE_USER_ACTION_LOADING';
export const DELETE_USER_ACTION_SUCCESS = 'DELETE_USER_ACTION_SUCCESS';
export const DELETE_USER_ACTION_ERROR = 'DELETE_USER_ACTION_ERROR';
